FROM ubuntu:16.04
MAINTAINER Jeganathan Swaminathan <http://www.tektutor.org> <jegan@tektutor.org>


#ENV HTTP_PROXY http://10.19.16.165:8080
#ENV HTTPS_PROXY https://10.19.16.165:8080

RUN apt-get -y update && apt-get -y install vim

RUN apt-get -y install tree
