- name: Demonstrates conditional installation
  hosts: all
  vars:
    provisioner_tool:  Docker
    automation_tool: Ansible
    greeting_msg: DevOps!

    proxy_conf:
       http_proxy: http://10.19.16.165:8080
       https_proxy: http://10.19.16.165:8080

  tasks:
    - name: Install nginx web server in Ubuntu
      when: ( ansible_os_family == "Debian" and ansible_distribution == "Ubuntu" )
      apt: name=nginx state=latest update_cache=yes
      #environment: "{{proxy_conf}}

    - name: Install epel release package in CentOS
      when: ( ansible_os_family == "RedHat" and ansible_distribution == "CentOS" )
      yum: name=epel-release state=latest
      #environment: "{{proxy_conf}}

    - name: Install nginx web server in CentOS 
      when: ( ansible_os_family == "RedHat" and ansible_distribution == "CentOS" )
      yum: name=nginx state=latest
      #environment: "{{proxy_conf}}
       
    - name: Configure web root folder in Ubuntu
      when: ( ansible_os_family == "Debian" and ansible_distribution == "Ubuntu" )
      copy: src=default dest=/etc/nginx/sites-available/default
      notify:
         - Restart nginx server

    - name: Configure web root folder in CentOS
      when: ( ansible_os_family == "RedHat" and ansible_distribution == "CentOS" )
      copy: src=default.conf dest=/etc/nginx/conf.d/default.conf
      notify:
         - Restart nginx server

    - name: Create web root folder
      file: path=/var/html mode=0777 state=directory

    - name: Deploy web page in nginx web server
      template: src=index.html.j2 dest=/var/html/index.html

  handlers:
     - name: Restart nginx server
       shell: service nginx restart
