- name: This playbook will demonstrate the use of list variable and looping
  hosts: all
  become: yes

  vars:
    - proxy_conf:
         http_proxy: http://10.19.16.165:8080
         https_proxy: https://10.19.16.165:8080

    - software_packages:
            - vim
            - tree
            - net-tools

  tasks:
   - name: Install the software utilities
     apt: name="{{item}}" state=latest update_cache=yes
     with_list: "{{software_packages}}"
     # environment: "{{proxy_conf}}"


